### PR TITLE
fix blocky renderer when camera is too close to penisobj

### LINKED ISSUE #2: IO demosiac not completely functional
Hello there 

the PC dic still become blocky when the distance between dic bone and camera is too close
disable the mosaic setup monobehavior itself after start() fix the problem
```
[HarmonyPatch(typeof(MozaicSetUp), "Start")]
class PatchMosaic
{
    static void Postfix(ref MozaicSetUp __instance)
    {
        __instance.enabled = false;
    }
}
```

### PR DESCRIPTION
**Pull request by r0ngk**
The patched part, for reference
```
private void Update()
{
	MozaObj.material.color = Color.white;
	CameraPos = Vector3.Distance(MainCamera.transform.position, PenisBone.transform.position);
	MozaObj.sharedMaterial.SetFloat("_BlockSize", Mathf.Clamp((CameraPos - 20f) * -1f + Mathf.Lerp(10f, 0f, (Camera.main.fieldOfView - 10f) / 100f * 2f), 12f, 30f) * GameClass.mozamoza);
	IL = Mathf.InverseLerp(1f, 10f, CameraPos);
	if (base.gameObject.name == "PC00")
	{
		PenisObj.sharedMaterial.SetFloat("_Moza", Mathf.Lerp(30f, 1000f, IL) * GameClass.mozamoza);
	}
}
```
in MozaicSetUp

### CODE REVIEW

File: IO_Demosaic/IO_Demosaic.cs [hunk 1]
```diff
@@ -9,7 +9,7 @@ namespace IO_Demosaic
     public class IO_Demosaic : BaseUnityPlugin
     {
         // Set version in BepInEx and in AssemblyInfo
-        public const string Version = "1.1";
+        public const string Version = "1.2";
```
Comment (ManlyMarco) [inline IO_Demosaic/IO_Demosaic.cs]:
```suggestion
        public const string Version = "1.1";
```
Do not change version numbers in PRs.

**Review by ManlyMarco — APPROVED** [review]
Looks good, thank you!

PS: If you're interested in making more PRs, see my profile page for info about a PR bounty I'm currently running.
